### ISSUE TITLE
borderRadius not applied

### ISSUE THREAD

**Issue by QuintinKrugerMC** [lightning-tv/core#19]
We have a component that sets the borderRadius of a View element 

![image](https://github.com/user-attachments/assets/11d88d4c-4313-4cf0-b0ac-842f54bc9edb)

![image](https://github.com/user-attachments/assets/7615c921-e997-4651-b376-b6ee130acbd4)

This is the result (16 px radius should be more defined)
![image](https://github.com/user-attachments/assets/67436c21-a65b-437f-b1e0-5aa8d7049a22)

Checking whether the radius was applied on the element we can confirm it is pulling through however it is not rendering as excpected 
![image](https://github.com/user-attachments/assets/6acf4fc8-8951-40a6-af4f-bbdac5548e48)

The versions for core, ui and solid are 
![image](https://github.com/user-attachments/assets/64fc7186-5c1e-4dbe-8077-7a61c05e8bca)

**Comment by t1mp4** [comment]
Yeah, seems like it's broken. Can't even create a circle. It appears to be working correctly in the @lightningjs/renderer.

I will look into it.

To reproduce you can clone https://github.com/lightning-tv/solid-starter-template and add the following element to `src/pages/app.tsx`:
```jsx
<View
  style={{
    x: 800,
    y: 600,
    width: 100,
    height: 100,
    color: 0x00ff00ff,
    borderRadius: 999999,
  }}
/>
```
