### ISSUE TITLE
SDF font issues

### ISSUE THREAD

**Issue by promentol** [lightning-tv/core#22]
What happens, if font.type == web ? that still renders sdf font? should we refactor? similar issue is also in Blits framework

https://github.com/lightning-tv/core/blob/5df3217c635c87dbba2b1ae9181c3ea3308b3ff9/src/lightningInit.ts#L36

**Comment by chiefcll** [comment]
There are only two value types which are valid `ssdf` and `msdf` - The fonts are loaded in the Renderer and don't have "Web" font - The other renderer is Canvas which can use built in ones. 

https://github.com/lightning-js/renderer/blob/9c01b8ba58e7b66ff1132231a504cf94f1db2857/src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts#L309

What are you trying to do?

**Comment by chiefcll** [comment]
I see the blits issue you were referring to
https://github.com/lightning-js/blits/issues/172

Solid won't have the same issue as we don't determine the engines at runtime like blits does. Let me know but I don't think this is an issue.

**Comment by chiefcll** [comment]
Further protected and will be out in the next release this week.
