### ISSUE TITLE
Updated $states

### ISSUE THREAD

**Issue by chiefcll** [lightning-tv/core#26]
Looking to update the Typescript for state styles.

Rather than allowing keys in style like

focus: {}
disabled: {}

You'd have to do

Option A)
// Slightly better performance
$states: {
  focus:{}
  disabled: {}
}

or

Option B)
// Much simpler migration path for current users
// no $states wrapper
$focus: {}
$disabled: {}

In this case the states = { $focus: true, $disabled } would also be prefixed with a $ to tie them together.

This would allow us to have tighter TS definitions and not allow random keys in the Style object.

**Comment by chiefcll** [comment]
I think I'm going with OptionB - much simpler migration path forward

**Comment by pecoram** [comment]
Option B is OK for me

**Comment by anthony9187** [comment]
so from a component syntax prospective, option A would look like this:
```
<Component
   style={{color: 'red'}}
   $states={{disabled: { color: 'grey'}}}
   state={{disabled: true}}
/>
```

while option B would look like this:
```
<Component
   style={{color: 'red', $disabled: { color: 'grey' }}}
   state={{$disabled: true}}
/>
```

correct?

If that's the case, I agree in leaning towards B. while the `$` adds a little visual overhead, I think keeping the state styles in the style object is a little cleaner and prevents us from needing three separate props to handle a state

**Comment by chiefcll** [comment]
The syntax is correct. You could still put everything in the style object you'd just have to do:

```js
const style = {
  ...normalStyles
  $states: { disabled: { color: 'grey'} }
}
```

All style does is copy it over to the element node.
