### ISSUE TITLE
Invalid key code from remote controller button

### ISSUE THREAD

**Issue by scailbc** [lightning-tv/core#28]
I'm testing on a LG TV, model 43UR80006LJ and I'm receiving some weird keyboard events.

This is form the Play button:

```
KeyboardEvent {
   code: "",
   key: "Unidentified",
   keyCode: 415,
   type: "keydown",
   which: 415,
   ...
}
```

And this is from the Pause button:

```
KeyboardEvent {
   code: "Pause",
   key: "",
   keyCode: 19,
   type: "keydown",
   which: 19,
   ...
}
```

The event is completely ignored, I think that the problem is in the focusManager:

```js
const key: KeyNameOrKeyCode = keypress.key || keypress.keyCode;
const mappedKeyHoldEvent = keyMapEntries[key];
```

Since the `key` property exists the `keyCode` is ignored, but since it has an invalid value the whole event is discarded. I can't simply use "Unidentified" as an alias because the Stop button has the same key.

I think this can easily be solved by doing `const mappedKeyHoldEvent = keyMapEntries[keypress.key] || keyMapEntries[keypress.keyCode];`, seems more robust.

Note: to be precise the remote controller I'm using is the virtual one used in the webOS TV [App Compatibility Test Suite](https://seller.lgappstv.com/seller/qna/RetrieveQnaList.lge), used to deploy the App in the LG store

**Comment by chiefcll** [comment]
Thanks for the detailed notes. Updated to check for entry of key or keyCode which should work. Just add entries for 19 and 419 etc...
